experiment_name: "yield_prediction_v1"
model_type: "gnn"
input_months: 4
batch_size: 32
data:
  data_path: "data/raw"
  additional_data: "data/"
  train: "data/"
  processed_graph: "data/processed/"
  train_img: "data/image_arrays_train"

model:
  learn: 0.001
  epoch: 50
  knn:
    k: 20
    E: 0.0001
  tcn:
    epoch: 300
    dropout: 0.1

models_saved: "models_saved/"
