experiment_name: "yield_prediction_v1"
model_type: "gnn"
input_months: 4
batch_size: 32
data:
  additional_data: "data/additional.csv"
  train: "data/Train.csv"
  test: "data/test_field_ids_with_year.csv"
  processed_graph: "data/processed/"
  train_img: "data/image_arrays_train"
  test_img: "data/image_arrays_test"
  submission: "data/"
model:
  learn: 0.001
  epoch: 1000
  knn:
    k: 20
    E: 0.0001
  tcn:
    epoch: 300
    dropout: 0.1
    hidden: [64, 128]
  gcn:
    hidden: 128

models_saved: "models_saved/"
